# Generated by Django 2.2.4 on 2019-08-19 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileRec',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField()),
                ('format', models.CharField(max_length=10)),
                ('date_added', models.DateField()),
                ('file_type', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'file_rec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRec',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=16)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_rec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('in_use', models.BooleanField()),
                ('user_type', models.CharField(db_column='user_type', max_length=6)),
            ],
            options={
                'db_table': 'verification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccessRec',
            fields=[
                ('user_email', models.OneToOneField(db_column='user_email', max_length=255, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='member_site.UserRec')),
                ('access_stamp', models.DateTimeField()),
                ('query_type', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'access_rec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminRec',
            fields=[
                ('email', models.OneToOneField(db_column='email', max_length=255, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='member_site.UserRec')),
            ],
            options={
                'db_table': 'admin_rec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SingerRec',
            fields=[
                ('email', models.OneToOneField(db_column='email', max_length=255, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='member_site.UserRec')),
                ('type', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'singer_rec',
                'managed': False,
            },
        ),
    ]
