# Generated by Django 2.2.4 on 2019-08-27 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessrec',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='adminrec',
            name='email',
        ),
        migrations.RemoveField(
            model_name='singerrec',
            name='email',
        ),
        migrations.DeleteModel(
            name='Verification',
        ),
        migrations.DeleteModel(
            name='AccessRec',
        ),
        migrations.DeleteModel(
            name='AdminRec',
        ),
        migrations.DeleteModel(
            name='SingerRec',
        ),
        migrations.DeleteModel(
            name='UserRec',
        ),
    ]
